Design_reportGetGrafic:
    path:  /design/reporte/getGrafic
    defaults: { _controller: DesignBundle:Design:getGrafic }
    requirements:
        _methods: POST

Design_reportListar:
    path:  /design/reporte/AbrirListar/{bkp}
    defaults: { _controller: DesignBundle:Design:abrirListar ,bkp: false}
    requirements:
        bkp: false|true
        _methods: POST
Design_reportAbrir:
    path:  /design/reporte/ReporteAbrir
    defaults: { _controller: DesignBundle:Design:reporteAbrir }
    requirements:
        _methods: POST
Design_reportSave:
    path:  /design/reporte/ReporteGuardar
    defaults: { _controller: DesignBundle:Design:reporteGuardar }
    requirements:
        _methods: POST
Design_reporteVer:
    path:  /design/reporte/ReporteVer
    defaults: { _controller: DesignBundle:Design:reporteVer }
    requirements:
        _methods: POST
Design_imagenListar:
    path:  /design/imagen/listar
    defaults: { _controller: DesignBundle:Design:imagenListar }
    requirements:
        _methods: POST
Design_ProcesarSql:
    path:  /design/sql/ProcesarSql
    defaults: { _controller: DesignBundle:Design:procesarSql }
    requirements:
        _methods: POST
Design_getFont:
    path:  /design/font/getFont
    defaults: { _controller: DesignBundle:Design:getFont }
    requirements:
        _methods: POST
        
Design_app:
    path:  /design/{controler}
    defaults: { _controller: DesignBundle:Design:design }
Design_ingreso:
    path:  /design
    defaults: { _controller: DesignBundle:Design:loadApp }
    
Design_ingreso2:
    path:  /
    defaults: { _controller: DesignBundle:Design:loadApp }    