Design_reportGetGrafic:
    path:  /design/reporte/getGrafic
    controller: Design\DesignBundle\Controller\DesignController::getGraficAction
    requirements:
        _methods: POST

Design_reportListar:
    path:  /design/reporte/AbrirListar/{bkp}
    controller: Design\DesignBundle\Controller\DesignController::abrirListarAction
    requirements:
        bkp: false|true
        _methods: POST
Design_reportAbrir:
    path:  /design/reporte/ReporteAbrir
    controller: Design\DesignBundle\Controller\DesignController::reporteAbrirAction
    requirements:
        _methods: POST
Design_reportSave:
    path:  /design/reporte/ReporteGuardar
    controller: Design\DesignBundle\Controller\DesignController::reporteGuardarAction
    requirements:
        _methods: POST
Design_reporteVer:
    path:  /design/reporte/ReporteVer
    controller: Design\DesignBundle\Controller\DesignController::reporteVerAction
    requirements:
        _methods: POST
Design_imagenListar:
    path:  /design/imagen/listar
    controller: Design\DesignBundle\Controller\DesignController::imagenListarAction
    requirements:
        _methods: POST
Design_ProcesarSql:
    path:  /design/sql/ProcesarSql
    controller: Design\DesignBundle\Controller\DesignController::procesarSqlAction
    requirements:
        _methods: POST
#Design_getFont:
#    path:  /design/font/getFont
#    controller: Design\DesignBundle\Controller\DesignController::getFont
#    requirements:
#        _methods: POST
        
#Design_app:
#    path:  /design/{controler}
#    controller: Design\DesignBundle\Controller\DesignController::design
Design_ingreso:
    path:  /pdf_diseño
    controller: Design\DesignBundle\Controller\DesignController::loadAppAction
    
Design_ingreso2:
    path:  /
    controller: Design\DesignBundle\Controller\DesignController::loadAppAction